[env:inkplate6plus]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    https://github.com/SolderedElectronics/Inkplate-Platformio-Library
monitor_speed = 115200
upload_speed = 115200
upload_flags = --no-stub
build_flags =
    -UARDUINO_ESP32_DEV
    -DARDUINO_INKPLATE6PLUS
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
